#!/bin/bash
## An example SLURM script for PU's Stellar cluster
#SBATCH -J Ex_Job                        ## Job name
#SBATCH --nodes=1                        ## Number of nodes requested
#SBATCH --ntasks-per-node=48             ## Number of cores requested per node (96/node on Stellar)
#SBATCH --time=03:00:00                  ## Maximum job runtime (HH:MM:SS)
#SBATCH --mail-type=all                  ## Request emails when the job begins and ends
#SBATCH --mail-user=your@email.here

exec=/path/to/executable/rfedipic

srun $exec > dedipic.${SLURM_JOBID}.out
